CREATE TABLE PROFESSOR
(
	CodP SERIAL NOT NULL,
	FirstName PERSON_NAME NOT NULL,
	LastName PERSON_NAME NOT NULL,
	Email EMAIL UNIQUE NOT NULL,
	Username VARCHAR(35) UNIQUE NOT NULL,
	Pw PASSWORD_D NOT NULL,

	PRIMARY KEY(CodP)
);

CREATE TABLE STUDENT
(
	StudentID SERIAL NOT NULL,
	FirstName PERSON_NAME NOT NULL,
	LastName PERSON_NAME NOT NULL,
	Email EMAIL UNIQUE NOT NULL,
	Username VARCHAR(35) UNIQUE NOT NULL,
	Pw PASSWORD_D NOT NULL,

	PRIMARY KEY(StudentID)
);

CREATE TABLE TEST
(
	CodTest SERIAL NOT NULL,
	Name TEST_NAME UNIQUE NOT NULL,
	CreationDateTime TIMESTAMP DEFAULT LOCALTIMESTAMP,
	StartingDateTime TIMESTAMP,
	ClosingDateTime TIMESTAMP,
	MinScore DECIMAL(4,3),
	CodP SERIAL NOT NULL,

	PRIMARY KEY(CodTest),

	FOREIGN KEY(CodP) REFERENCES PROFESSOR(CodP)
);

CREATE TABLE LECTURE
(
	CodL SERIAL NOT NULL
	Title VARCHAR(30) NOT NULL UNIQUE,
	Link VARCHAR(512),
	CodP SERIAL NOT NULL,
	CodC SERIAL NOT NULL,

	PRIMARY KEY(CodL),

	FOREIGN KEY(CodP) REFERENCES PROFESSOR(CodP),
	FOREIGN KEY(CodC) REFERENCES CLASS(CodC)
);

CREATE TABLE OPEN_QUIZ
(
	CodOQ SERIAL NOT NULL,
	Question VARCHAR(512) NOT NULL,
	MaxScore DECIMAL(4,3) NOT NULL,
	MinScore DECIMAL(4,3) NOT NULL,
	MaxLength INT DEFAULT 1024,
	CodTest SERIAL NOT NULL,

	PRIMARY KEY(CodOQ),
	FOREIGN KEY(CodTest) REFERENCES TEST(CodTest)
);

CREATE TABLE CLOSED_QUIZ
(
	CodCQ SERIAL NOT NULL,
	Question VARCHAR(512) NOT NULL,
	AnswerA VARCHAR(128) NOT NULL,
	AnswerB VARCHAR(128) NOT NULL,
	AnswerC VARCHAR(128),
	AnswerD VARCHAR(128),
	RightAnswer CLOSED_ANSWER NOT NULL,
	ScoreIfRight DECIMAL(4,3) NOT NULL,
	ScoreIfWrong DECIMAL(4,3) NOT NULL,
	CodTest SERIAL NOT NULL,

	PRIMARY KEY(CodCQ),
	FOREIGN KEY(CodTest) REFERENCES TEST(CodTest)
);

CREATE TABLE CLASS
(
	CodC SERIAL NOT NULL,
	Name VARCHAR(50) NOT NULL UNIQUE,
	Year INT DEFAULT DATE_PART('year', LOCALTIMESTAMP),
	CFU VALID_CFU NOT NULL,
	CodP SERIAL,

	PRIMARY KEY(CodC),

	FOREIGN KEY(CodP) REFERENCES PROFESSOR(CodP)
);

CREATE TABLE TAKE
(
	CodC SERIAL NOT NULL,
	StudentID SERIAL NOT NULL,

	PRIMARY KEY(CodC, StudentID),

	FOREIGN KEY(CodC) REFERENCES CLASS(CodC),
	FOREIGN KEY(StudentID) REFERENCES STUDENT(StudentID)
);

CREATE TABLE OPEN_ANSWER
(
	CodOA SERIAL NOT NULL,
	GivenAnswer VARCHAR(1024),
	Score DECIMAL(4,3) DEFAULT 0,
	CodOQ SERIAL NOT NULL,
	CodTest_Taken SERIAL NOT NULL,
	StudentID_Taking SERIAL NOT NULL,

	PRIMARY KEY(CodOA),

	FOREIGN KEY(CodOQ) REFERENCES OPENQUIZ(CodOQ),
	FOREIGN KEY(CodTest_Taken) REFERENCES TEST_TAKEN(CodTest),
	FOREIGN KEY(StudentID_Taking) REFERENCES TEST_TAKEN(StudentID)
);

CREATE TABLE CLOSED_ANSWER
(
	CodCA SERIAL NOT NULL,
	GivenAnswer CHAR,
	Score DECIMAL(4,3) DEFAULT 0,
	CodCQ SERIAL NOT NULL,
	CodTest_Taken SERIAL NOT NULL,
	StudentID_Taking SERIAL NOT NULL,

	PRIMARY KEY(CodCA),

	FOREIGN KEY(CodCQ) REFERENCES CLOSEDQUIZ(CodOQ),
	FOREIGN KEY(CodTest_Taken) REFERENCES TEST_TAKEN(CodTest),
	FOREIGN KEY(StudentID_Taking) REFERENCES TEST_TAKEN(StudentID)
);

CREATE TABLE TEST_TAKEN
(
	CodTest SERIAL NOT NULL,
	StudentID SERIAL NOT NULL,
	Revised BOOLEAN DEFAULT FALSE,
	Passed BOOLEAN,
	TotalScore DECIMAL(5,4) DEFAULT 0,

	PRIMARY KEY(CodTest, StudentID),

	FOREIGN KEY(CodTest) REFERENCES TEST(CodTest),
	FOREIGN KEY(StudentID) REFERENCES STUDENT(StudentID)
)
