CREATE FUNCTION UCQS_function()
	RETURNS TRIGGER
AS $$
	BEGIN
		IF EXISTS  (SELECT *
					FROM CLOSEDANSWER AS CA, CLOSEDQUIZ AS CQ
					WHERE CA.CodCQ = CQ.CodCQ
						AND CA.CodCA = NEW.CodCA
						AND CA.GivenAnswer = CQ.RightAnswer) THEN
		
			UPDATE CLOSEDANSWER
			SET Score = (SELECT ScoreIfRight
						 FROM CLOSEDANSWER AS CA, CLOSEDQUIZ AS CQ
						 WHERE CA.CodCQ = CQ.CodCQ
							AND CA.CodCA = NEW.CodCA);
		
		ELSE

			UPDATE CLOSEDANSWER
			SET Score = (SELECT ScoreIfWrong
						 FROM CLOSEDANSWER AS CA, CLOSEDQUIZ AS CQ
						 WHERE CA.CodCQ = CQ.CodCQ
							AND CA.CodCA = NEW.CodCA);

		END IF;

		RETURN NEW;
	END; $$ 
	LANGUAGE PLPGSQL;


CREATE TRIGGER Update_CQ_Score
AFTER INSERT ON CLOSEDANSWER
FOR EACH ROW
EXECUTE PROCEDURE UCQS_function();